/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DishCreateDto { 
    name: string;
    preparedAt: string;
    calories?: number;
    protein?: number;
    fat?: number;
    carbohydrates?: number;
    recipeIds?: Array<string>;
    ingredientIds?: Array<string>;
}

