/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type MealCreateDto = {
  mealType: MealCreateDto.MealTypeEnum;
  dateTime: string;
  dishIds: Array<string>;
};
export namespace MealCreateDto {
  export const MealTypeEnum = {
    Breakfast: 'BREAKFAST',
    Lunch: 'LUNCH',
    Dinner: 'DINNER',
    Snack: 'SNACK',
  } as const;
  export type MealTypeEnum = (typeof MealTypeEnum)[keyof typeof MealTypeEnum];
}
