export * from './dishController.service';
import { DishControllerService } from './dishController.service';
export * from './ingredientController.service';
import { IngredientControllerService } from './ingredientController.service';
export * from './mealController.service';
import { MealControllerService } from './mealController.service';
export * from './recipeController.service';
import { RecipeControllerService } from './recipeController.service';
export * from './sampleDataController.service';
import { SampleDataControllerService } from './sampleDataController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [DishControllerService, IngredientControllerService, MealControllerService, RecipeControllerService, SampleDataControllerService, UserControllerService];
